### ISSUE TITLE
EntraId Demo:  An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.

### ISSUE THREAD

**Issue by Andreas-Klapproth** [oidcproxydotnet/OidcProxy.Net#222]
Hello guys,

i want to create a new Bff application and downloaded the sample for entra id from here [demo App](https://github.com/oidcproxydotnet/OidcProxy.Net/tree/main/docs/demos/Authentication-Gateways/AzureAd/src)

If i run the bff app and the SPA app there are some  cards like: 
- `/account/login`
- `/account/end-session`
- `/account/me` 

If i click on `/account/login` nothing happen. If i enter enter `https://localhost:8443/.auth/login`  i get redirected to the azure login form and can enter my login data.
But then i get an error: 
```
System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at OidcProxy.Net.EntraId.EntraIdIdentityProvider.ObtainDiscoveryDocument(String endpointAddress)
   at OidcProxy.Net.OpenIdConnect.OpenIdConnectIdentityProvider.GetDiscoveryDocument()
   at OidcProxy.Net.OpenIdConnect.OpenIdConnectIdentityProvider.GetTokenAsync(String redirectUri, String code, String codeVerifier, String traceIdentifier)
   at OidcProxy.Net.Endpoints.CallbackEndpoint.Get(HttpContext context, AuthSession authSession, ILogger logger, IRedirectUriFactory redirectUriFactory, ProxyOptions proxyOptions, IIdentityProvider identityProvider, ITokenParser tokenParser, IAuthenticationCallbackHandler authenticationCallbackHandler)
   at OidcProxy.Net.Endpoints.CallbackEndpoint.Get(HttpContext context, AuthSession authSession, ILogger logger, IRedirectUriFactory redirectUriFactory, ProxyOptions proxyOptions, IIdentityProvider identityProvider, ITokenParser tokenParser, IAuthenticationCallbackHandler authenticationCallbackHandler)
   at OidcProxy.Net.Endpoints.CallbackEndpoint.Get(HttpContext context, AuthSession authSession, ILogger logger, IRedirectUriFactory redirectUriFactory, ProxyOptions proxyOptions, IIdentityProvider identityProvider, ITokenParser tokenParser, IAuthenticationCallbackHandler authenticationCallbackHandler)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
   at OidcProxy.Net.ModuleInitializers.ModuleInitializer.<>c.<<UseOidcProxy>b__3_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**In Entra id:**
platform: `Web`
redirect Uri is set to : `https://localhost:8444/.auth/login/callback`

nuget:-package: `nuget\packages\oidcproxy.net.entraid\3.3.0`

here my appsetings. json
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "OidcProxy": {
    "EntraId": {
      "ClientId": "7xxxxxxxxxx....",
      "ClientSecret": "Hxxxxxxxxxx...",
      "TenantId": "0axxxxxxxxxxxxx...",
      "Scopes": [
        "openid",
        "profile",
        "offline_access"
      ]
    },
    "ReverseProxy": {
      "Routes": {
        "spa": {
          "ClusterId": "spa",
          "Match": {
            "Path": "/{*any}"
          }
        },
        "api": {
          "ClusterId": "api",
          "Match": {
            "Path": "/api/{*any}"
          }
        }
      },
      "Clusters": {
        "spa": {
          "Destinations": {
            "spa": {
              "Address": "http://localhost:4200/"
            }
          }
        },
        "api": {
          "Destinations": {
            "api": {
              "Address": "http://localhost:8080/"
            }
          }
        }
      }
    }
  }
}
```

so what am i missing?

_Is it correct that the angular example do nothing on click on the specific cards?_ => **update**: ok i see this was not updated in the demo. [In this demo](https://github.com/oidcproxydotnet/OidcProxy.Net/blob/main/docs/demos/spa-bffs/auth0/src/spa%2Bbff/ClientApp/src/app/app.component.html) it is correct

If i test the Auth0 demo everything works as accepted, maybe some issue with **EntraId**?

I am on a local windows 11 machine

Thank you guys!

**Comment by Andreas-Klapproth** [comment]
Update: if i add: 
` "DiscoveryEndpoint": "https://login.microsoftonline.com/xxxxxxxxx/v2.0/.well-known/openid-configuration",` 
then it seems to work.

**Comment by appie2go** [comment]
Does that mean the issue can be closed?

**Comment by Andreas-Klapproth** [comment]
i think so. On my private Azure Account it works well, but in my organization account there is another problem. 

Thanks

**Comment by appie2go** [comment]
Is it a configuration issue? Can you describe the steps to reproduce?

**Comment by appie2go** [comment]
Closed due to inactivity
